#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
# shellcheck disable=SC2034
RED='\033[0;31m'
NC='\033[0m' # No Color

# выходим при ошибке
set -e

print_image() {
    local image=("$@")
    for line in "${image[@]}"; do
        echo -e "$line"
    done
}

OS_ID=$(grep '^ID=' /etc/os-release | cut -d'=' -f2 | tr -d '"')
OS_CODENAME=$(lsb_release -cs)

if [[ "$OS_ID" != "debian" && "$OS_ID" != "ubuntu" ]]; then
    echo -e "${RED}Этот скрипт поддерживает только Debian и Ubuntu${NC}"
    exit 1
fi

# docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker не найден. Устанавливаем Docker...${NC}"
    
    sudo apt update
    sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
    sudo curl -fsSL https://download.docker.com/linux/${OS_ID}/gpg | sudo apt-key add -

    sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/${OS_ID} $(lsb_release -cs) stable"

    sudo apt update
    sudo apt install -y docker-ce

    echo -e "${GREEN}Docker установлен.${NC}"
else
    echo -e "${GREEN}Docker уже установлен.${NC}"
fi

# docker compose
if ! command -v docker-compose &> /dev/null; then
    echo -e "${YELLOW}Docker Compose не найден. Устанавливаем Docker Compose...${NC}"
    
    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    echo -e "${GREEN}Docker Compose установлен.${NC}"
else
    echo -e "${GREEN}Docker Compose уже установлен.${NC}"
fi

image=(
    ""
    " ██████╗░░█████╗░███╗░░██╗███████╗"
    " ██╔══██╗██╔══██╗████╗░██║██╔════╝"
    " ██║░░██║██║░░██║██╔██╗██║█████╗░░"
    " ██║░░██║██║░░██║██║╚████║██╔══╝░░"
    " ██████╔╝╚█████╔╝██║░╚███║███████╗"
    " ╚═════╝░░╚════╝░╚═╝░░╚══╝╚══════╝"
)

print_image "${image[@]}"
docker-compose --version
