version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # если порт 6379 занят, измените на любой другой
    volumes:
      - redis_data:/data
    restart: always